### ISSUE TITLE
Move this repo to https://github.com/Julia-Streamers

### ISSUE THREAD

**Issue by logankilpatrick** [Julia-Streamers/TwitchTools.jl#1]
Hey @wookay would you be okay joining forces and moving this to the https://github.com/Julia-Streamers org? This way we can bring in new maintainers and grow this package/community!

**Comment by wookay** [comment]
currently, it only used to get details about some twitch clip. for that reason, it's not registered yet to the General repository. and yeah. it's a great idea that using this package for Julia-Streamers org. great thanks and please invite me to Julia-Streamers org.

**Comment by logankilpatrick** [comment]
Will do, I’ll get you owner access and that way you can transfer the repo there.

**Comment by wookay** [comment]
okay. please tell me when it ready to transfer this repo.

**Comment by logankilpatrick** [comment]
Sweet, you should have been Invited and made an owner!

**Comment by wookay** [comment]
there's a forked repository on Julia-Streamers org.
I got `Julia-Streamers/TwitchTools.jl already exists` message during to try transfer this repo.

**Comment by Wikunia** [comment]
@thecedarprince just deleted it :)

**Comment by wookay** [comment]
@Wikunia  thanks!

**Comment by TheCedarPrince** [comment]
Awesome! I will close this issue as we now have moved this repo to the Julia Streamers organization. Huge thanks to @wookay for doing this! :smile:
